from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass
from typing import Any
from urllib.request import Request, urlopen

from .base import ProviderAdapter, ProviderRequest, ProviderResponse, StepType
from .openai_adapter import OpenAIProviderAdapter
from .openrouter_adapter import OpenRouterProviderAdapter


@dataclass(slots=True)
class ProviderCatalog:
    provider: str
    step: StepType
    models: list[str]
    model_pricing: dict[str, dict[str, Any]] | None = None


class MockProviderAdapter(ProviderAdapter):
    def __init__(self, provider_name: str, supported: dict[StepType, list[str]]) -> None:
        self._provider_name = provider_name
        self._supported = supported

    def name(self) -> str:
        return self._provider_name

    def supports(self, step: StepType, model: str) -> bool:
        return model in self._supported.get(step, [])

    async def invoke(self, req: ProviderRequest) -> ProviderResponse:
        digest = hashlib.sha1(
            f"{self._provider_name}:{req.step}:{req.model}:{req.prompt}:{req.input}:{req.params}".encode("utf-8")
        ).hexdigest()[:12]
        output: dict[str, Any] = {
            "provider": self._provider_name,
            "step": req.step,
            "model": req.model,
            "artifact_id": f"{req.step}-{digest}",
            "summary": f"Generated by {self._provider_name}/{req.model}",
        }
        usage = {
            "inputTokens": max(64, len(str(req.input)) // 3),
            "outputTokens": 256,
            "seconds": 2,
        }
        if req.step == "video":
            output["video_id"] = f"vid-{digest}"
            output["status"] = "queued"
        elif req.step == "image":
            output["image_data_url"] = (
                "data:image/png;base64,"
                "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9sYuk3QAAAAASUVORK5CYII="
            )
            output["artifact_mode"] = "image"
        return ProviderResponse(output=output, usage=usage, raw={"mock": True})

    async def get_video_status(self, job_id: str) -> ProviderResponse:
        return ProviderResponse(
            output={
                "provider": self._provider_name,
                "step": "video",
                "artifact_id": job_id,
                "video_id": job_id,
                "status": "completed",
                "progress": 100,
            },
            usage={},
            raw={"mock": True},
        )

    async def download_video(self, job_id: str) -> tuple[bytes, str]:
        return f"mock video content for {job_id}".encode("utf-8"), "video/mp4"


class ProviderRegistry:
    _OPENROUTER_MODELS_CACHE: list[dict[str, Any]] | None = None
    _OPENROUTER_MODELS_CACHE_TS: float = 0.0
    _OPENROUTER_MODELS_CACHE_TTL_SEC: int = 600

    _SUPPORTED: dict[str, dict[StepType, list[str]]] = {
        "openrouter": {
            "chunk": [
                "openai/gpt-5-mini",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
                "deepseek/deepseek-chat-v3.1",
            ],
            "script": [
                "openai/gpt-5",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
                "deepseek/deepseek-chat-v3.1",
            ],
            "shot_detail": [
                "openai/gpt-5",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
            ],
            "consistency": [
                "openai/gpt-5",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
            ],
            "image": [
                "openai/gpt-5",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
            ],
            "video": [
                "openai/gpt-5",
                "anthropic/claude-sonnet-4",
                "google/gemini-2.5-pro",
            ],
            "tts": [
                "openai/gpt-5-mini",
                "google/gemini-2.5-pro",
            ],
        },
        "google": {
            "chunk": ["gemini-2.5-flash-lite"],
            "script": ["gemini-2.5-pro"],
            "image": ["imagen-4"],
            "video": ["veo-3.1"],
            "consistency": ["gemini-2.5-pro"],
        },
        "openai": {
            "chunk": ["gpt-5-mini", "gpt-5"],
            "script": ["gpt-5"],
            "shot_detail": ["gpt-5"],
            "image": ["gpt-image-1.5", "gpt-image-1"],
            "video": ["sora-2"],
            "tts": ["gpt-4o-mini-tts"],
            "consistency": ["gpt-5"],
        },
        "anthropic": {
            "script": ["claude-sonnet-4"],
            "shot_detail": ["claude-sonnet-4"],
            "consistency": ["claude-sonnet-4"],
        },
        "runway": {
            "image": ["runway-gen4-image"],
            "video": ["runway-gen4-turbo"],
        },
        "deepseek": {
            "chunk": ["deepseek-chat"],
            "script": ["deepseek-chat"],
        },
        "azure": {
            "tts": ["azure-neural-tts"],
        },
        "elevenlabs": {
            "tts": ["elevenlabs-multilingual-v2"],
        },
    }

    def __init__(self) -> None:
        self._adapters: dict[str, ProviderAdapter] = {}
        for provider, supported in self._SUPPORTED.items():
            if provider == "openrouter":
                adapter = OpenRouterProviderAdapter(supported)
                self._adapters[provider] = adapter if adapter.is_configured() else MockProviderAdapter(provider, supported)
                continue
            if provider == "openai":
                adapter = OpenAIProviderAdapter(supported)
                self._adapters[provider] = adapter if adapter.is_configured() else MockProviderAdapter(provider, supported)
                continue
            self._adapters[provider] = MockProviderAdapter(provider, supported)

    def list_catalog(self) -> list[ProviderCatalog]:
        catalogs: list[ProviderCatalog] = []
        openrouter_catalog = self._load_openrouter_catalog()
        if openrouter_catalog:
            catalogs.extend(openrouter_catalog)
        for provider, step_map in self._SUPPORTED.items():
            if provider == "openrouter":
                continue
            for step, models in step_map.items():
                catalogs.append(ProviderCatalog(provider=provider, step=step, models=models, model_pricing={}))
        return catalogs

    def resolve(self, provider: str) -> ProviderAdapter:
        if provider not in self._adapters:
            raise ValueError(f"Unsupported provider: {provider}")
        return self._adapters[provider]

    def suggest_model(self, step: StepType) -> tuple[str, str]:
        if step in {"chunk", "script", "shot_detail", "consistency", "image"}:
            openrouter_catalog = self._load_openrouter_catalog()
            for item in openrouter_catalog:
                if item.step == step and item.models:
                    if step in {"chunk", "script", "shot_detail", "consistency"}:
                        for preferred in (
                            "openrouter/auto",
                            "google/gemini-2.5-pro",
                            "anthropic/claude-sonnet-4",
                            "openai/gpt-5",
                        ):
                            if preferred in item.models:
                                return item.provider, preferred
                    return item.provider, item.models[0]
        if step in {"chunk", "script", "shot_detail", "consistency"}:
            preferred_order = ["openrouter", "openai", "anthropic", "google", "deepseek", "runway", "azure", "elevenlabs"]
        elif step == "image":
            preferred_order = ["openrouter", "openai", "google", "runway", "anthropic", "deepseek", "azure", "elevenlabs"]
        else:
            preferred_order = ["openai", "runway", "google", "openrouter", "anthropic", "deepseek", "azure", "elevenlabs"]
        for provider in preferred_order:
            step_map = self._SUPPORTED.get(provider, {})
            models = step_map.get(step, [])
            if models:
                return provider, models[0]
        raise ValueError(f"No model configured for step: {step}")

    def _load_openrouter_catalog(self) -> list[ProviderCatalog]:
        adapter = self._adapters.get("openrouter")
        if not isinstance(adapter, OpenRouterProviderAdapter) or not adapter.is_configured():
            return []
        models = self._fetch_openrouter_models()
        if not models:
            return []

        text_models: list[str] = []
        image_models: list[str] = []
        audio_models: list[str] = []
        pricing_map: dict[str, dict[str, Any]] = {}
        for model in models:
            model_id = str(model.get("id") or "").strip()
            if not model_id:
                continue
            architecture = model.get("architecture") or {}
            output_modalities = {str(item) for item in architecture.get("output_modalities") or []}
            pricing = model.get("pricing") or {}
            if isinstance(pricing, dict):
                pricing_map[model_id] = {
                    "input": pricing.get("prompt"),
                    "output": pricing.get("completion"),
                    "request": pricing.get("request"),
                    "image": pricing.get("image"),
                }
            if "text" in output_modalities:
                text_models.append(model_id)
            if "image" in output_modalities:
                image_models.append(model_id)
            if "audio" in output_modalities:
                audio_models.append(model_id)

        text_models = sorted(dict.fromkeys(text_models))
        image_models = sorted(dict.fromkeys(image_models))
        audio_models = sorted(dict.fromkeys(audio_models))
        return [
            ProviderCatalog(provider="openrouter", step="chunk", models=text_models, model_pricing=pricing_map),
            ProviderCatalog(provider="openrouter", step="script", models=text_models, model_pricing=pricing_map),
            ProviderCatalog(provider="openrouter", step="shot_detail", models=text_models, model_pricing=pricing_map),
            ProviderCatalog(provider="openrouter", step="consistency", models=text_models, model_pricing=pricing_map),
            ProviderCatalog(provider="openrouter", step="image", models=image_models, model_pricing=pricing_map),
            ProviderCatalog(provider="openrouter", step="tts", models=audio_models, model_pricing=pricing_map),
        ]

    def _fetch_openrouter_models(self) -> list[dict[str, Any]]:
        now = time.time()
        if (
            self.__class__._OPENROUTER_MODELS_CACHE is not None
            and now - self.__class__._OPENROUTER_MODELS_CACHE_TS < self.__class__._OPENROUTER_MODELS_CACHE_TTL_SEC
        ):
            return self.__class__._OPENROUTER_MODELS_CACHE or []

        try:
            api_key = os.getenv("N2V_OPENROUTER_API_KEY", "").strip()
            payload = None
            if api_key:
                req = Request(
                    "https://openrouter.ai/api/v1/models/user",
                    headers={
                        "User-Agent": "n2v-provider-registry/1.0",
                        "Authorization": f"Bearer {api_key}",
                    },
                )
                with urlopen(req, timeout=20) as response:
                    payload = json.loads(response.read().decode("utf-8"))
            if payload is None:
                req = Request("https://openrouter.ai/api/v1/models", headers={"User-Agent": "n2v-provider-registry/1.0"})
                with urlopen(req, timeout=20) as response:
                    payload = json.loads(response.read().decode("utf-8"))
            models = payload.get("data") or []
            if isinstance(models, list):
                self.__class__._OPENROUTER_MODELS_CACHE = models
                self.__class__._OPENROUTER_MODELS_CACHE_TS = now
                return models
        except Exception:  # noqa: BLE001
            return []
        return []
